import type { Metadata } from "next";

import "lenis/dist/lenis.css";
import ReactLenis from "lenis/react";

import "./globals.css";

import localFont from "next/font/local";

import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: make the scrollbar invisible
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactLenis root options={{ lerp: 0.1, smoothWheel: true }}>
          {children}
          <Toaster />
        </ReactLenis>
      </body>
    </html>
  );
}
